### ISSUE TITLE
게시판 정렬 기준이 확장변수일 경우 서버 오류 발생함.

### ISSUE THREAD

**Issue by hyunixxx1230** [cydemo/xe-addon-ap_extra_search#2]
일반적인 사용 환경  - 정렬기준이 기본제공 값일 경우라면 문제가 발생하지 않는데
게시판 정렬 기준이 확장변수일 경우 해당 게시판 접근 시 무조건 서버오류가 발생됩니다.

Query Error: SQLSTATE[42S22] : Column not found: 1054 Unknown column 'document.확장변수명' in 'order clause' (code -1)

**Comment by cydemo** [comment]
네, 0.5.2 버전으로 업데이트하였습니다.
